name: business_card
description: Business card application of Renzo Ventura

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/renzo-cropped.png
  fonts:
    - family: Tomorrow-Light
      fonts:
        - asset: fonts/Tomorrow-Light.ttf
    - family: Tomorrow-ExtraLight
      fonts:
        - asset: fonts/Tomorrow-ExtraLight.ttf
